---
title: "r practice"
output: html_document
author: Hong Jiang
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, include=TRUE, message=FALSE}
library(tidyverse)
library(DBI)
library(ggplot2)
library(heatmaply)
library(dplyr)
```
```{r load}
db <- dbConnect(RSQLite::SQLite(), "/shared/home/phingamp/medbioinfo_folder/pascal/central_database/sample_collab.db")
join <- dbGetQuery(db, 'select * from (bracken_abundances_long abu left join sample_annot using(run_accession))')
join_tibble = as_tibble(join)
```
```{r make_table}
join_tibble %in%  select(run_accession, taxon_name, fraction_total_reads) %>% filter()
```
```{r make_table}
columns <- join_tibble %>% select(run_accession, taxon_name, fraction_total_reads)
virus <- columns[grepl('virus', columns$taxon_name),]
pseudo_count = min(filter(virus, fraction_total_reads>0)$fraction_total_reads)
virus_log = virus %>% mutate(log_fraction=log2(fraction_total_reads+pseudo_count))
virus_log_wide = pivot_wider(virus_log, id_cols = run_accession, names_from = taxon_name, values_from = log_fraction)
```
```{r sample_heatmap}
ggplot(virus_log, aes(run_accession, taxon_name))+ geom_raster(aes(fill=log_fraction)) +
   theme_bw()+
  scale_fill_gradientn(colours=c("royalblue","white","yellow"))+
  theme(axis.text.y=element_blank())
```
```{r heatmaply}
df = as.data.frame(virus_log_wide)
df[is.na(df)] <- 0
annot_df <- as.data.frame(join_tibble)
colside_annot_df <- annot_df[,c('run_accession', 'nuc')]
heatmaply(df)
pdf('test.pdf')
#df <- normalize(mtcars)
x <- c(1:100)
random_y <- rnorm(100, mean = 0)
data <- data.frame(x, random_y)
library(plotly)
fig = plot_ly(data, x = ~x, y = ~random_y, type = 'scatter', mode = 'lines')
kaleido(fig, 'test.pdf')
dev.off()
library(plotly)
library(plyr)

tg <- ddply(ToothGrowth, c("supp", "dose"), summarise, length=mean(len))
heatmaply(df[,"annot_example"], Colv=F)
plot_ly(tg, x = ~dose, y = ~length, type = 'scatter', mode = 'lines', linetype = ~supp, color = I('black'), file = "heatmaply_plot_test.pdf") 
df$annot_example <- c(rep('A', 16), rep('B',16))
col_side_annot_1 <- data.frame()
colnames(col_side_annot_1) <- colnames(df)
col_side_annot_1 <- rbind(col_side_annot_1, rep('A',ncol(col_side_annot_1)))
heatmap(col_side_colors)
```